ALTER TABLE earthquakes
    ALTER COLUMN latitude TYPE DOUBLE PRECISION USING latitude::DOUBLE PRECISION,
    ALTER COLUMN longitude TYPE DOUBLE PRECISION USING longitude::DOUBLE PRECISION,
    ALTER COLUMN mag TYPE DOUBLE PRECISION USING mag::DOUBLE PRECISION,
    ALTER COLUMN depth TYPE DOUBLE PRECISION USING depth::DOUBLE PRECISION,
    ALTER COLUMN time TYPE TIMESTAMP USING time::TIMESTAMP;
